server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 192.168.101.65
      port: 7379
      password: 123456

  mvc:
    view:
      prefix: /templates/
      suffix: .html


mybatis-plus:
  mapper-locations: classpath*:site/bzyl/shortlink/project/dao/mapper/*.xml
  type-aliases-package: site.bzyl.shortlink.project.dao.entity
